### ISSUE TITLE
npx create-expo-stack not working.

### ISSUE THREAD

**Issue by Novexonl** [roninoss/create-expo-stack#367]
Let's get started!
│
◇  A folder with the name '' already exists. Do you want to delete it?
│  Yes
│
◇  Deleted existing directory: 
│
◇  Would you like to use TypeScript with this project?
│  Yes
Good call, now using TypeScript! 🚀
│
◇
We've detected npm v10.7.0 as your preferred package manager.
Would you like to continue using it?
│  Yes
│
◇  What would you like to use for Navigation?
│  Expo Router
│
◇  What type of navigation would you like to use?
│  Drawer + Tabs
│
◇  What would you like to use for styling?
│  NativeWind
You'll be styling with ease using Nativewind!
│
◇  What would you like to use for authentication?
│  Supabase
│
◇  Do you want to setup EAS
│  Yes
We'll setup EAS for you.
│
◇  Would you like to save this configuration for future use?
│  No

Your project configuration:
{
  projectName: '',
  packages: [
    {
      name: 'expo-router',
      type: 'navigation',
      options: { type: 'drawer + tabs' }
    },
    { name: 'nativewind', type: 'styling' },
    { name: 'supabase', type: 'authentication' }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'npm',
    eas: true
  }
}

To recreate this project, run:
  npx create-expo-stack  --expo-router --drawer+tabs --nativewind --supabase  --eas
sh: 0: getcwd() failed: No such file or directory
/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli/validate-engines.js:31
    throw err
    ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:144:28)
    at process.cwd (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:71:19)
    at new Npm (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/npm.js:66:19)
    at module.exports (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli/entry.js:20:15)
    at module.exports (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli/validate-engines.js:39:10)
    at module.exports (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli.js:4:31)
    at Object.<anonymous> (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

Node.js v20.15.1

Oops, something went wrong while creating your project 😢

If this was unexpected, please open an issue: https://github.com/roninoss/create-expo-stack#reporting-bugs--feedback

/home/codespace/.npm/_npx/b7475f0f52fd459b/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Command failed: npm --version
sh: 0: getcwd() failed: No such file or directory
/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli/validate-engines.js:31
    throw err
    ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:144:28)
    at process.cwd (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:71:19)
    at new Npm (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/npm.js:66:19)
    at module.exports (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli/entry.js:20:15)
    at module.exports (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli/validate-engines.js:39:10)
    at module.exports (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/lib/cli.js:4:31)
    at Object.<anonymous> (/usr/local/share/nvm/versions/node/v20.15.1/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

Node.js v20.15.1

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at getVersionForPackageManager (/home/codespace/.npm/_npx/b7475f0f52fd459b/node_modules/create-expo-stack/build/utilities/getPackageManager.js:90:46)
    at configureProjectFiles (/home/codespace/.npm/_npx/b7475f0f52fd459b/node_modules/create-expo-stack/build/utilities/configureProjectFiles.js:357:87)
    at /home/codespace/.npm/_npx/b7475f0f52fd459b/node_modules/create-expo-stack/build/commands/create-expo-stack.js:343:63
    at Generator.next (<anonymous>)
    at fulfilled (/home/codespace/.npm/_npx/b7475f0f52fd459b/node_modules/create-expo-stack/build/commands/create-expo-stack.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 7,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1333) [Uint8Array] [
      115, 104,  58,  32,  48,  58,  32, 103, 101, 116,  99, 119,
      100,  40,  41,  32, 102,  97, 105, 108, 101, 100,  58,  32,
       78, 111,  32, 115, 117,  99, 104,  32, 102, 105, 108, 101,
       32, 111, 114,  32, 100, 105, 114, 101,  99, 116, 111, 114,
      121,  10,  47, 117, 115, 114,  47, 108, 111,  99,  97, 108,
       47, 115, 104,  97, 114, 101,  47, 110, 118, 109,  47, 118,
      101, 114, 115, 105, 111, 110, 115,  47, 110, 111, 100, 101,
       47, 118,  50,  48,  46,  49,  53,  46,  49,  47, 108, 105,
       98,  47, 110, 111,
      ... 1233 more items
    ]
  ],
  pid: 8905,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1333) [Uint8Array] [
    115, 104,  58,  32,  48,  58,  32, 103, 101, 116,  99, 119,
    100,  40,  41,  32, 102,  97, 105, 108, 101, 100,  58,  32,
     78, 111,  32, 115, 117,  99, 104,  32, 102, 105, 108, 101,
     32, 111, 114,  32, 100, 105, 114, 101,  99, 116, 111, 114,
    121,  10,  47, 117, 115, 114,  47, 108, 111,  99,  97, 108,
     47, 115, 104,  97, 114, 101,  47, 110, 118, 109,  47, 118,
    101, 114, 115, 105, 111, 110, 115,  47, 110, 111, 100, 101,
     47, 118,  50,  48,  46,  49,  53,  46,  49,  47, 108, 105,
     98,  47, 110, 111,
    ... 1233 more items
  ]
}

Node.js v20.15.1`
`

install the pack

not installing

no idea

its not installing the cli is not working

1. npx create-expo-pack
2. follow the steps
3. andddd error
4.

**Comment by dannyhw** [comment]
Seems like npm --version failed?

What OS is this on?

**Comment by danstepanov** [comment]
closing this as there has been no response
