### ISSUE TITLE
upgrade nwui-cli to latest

### ISSUE THREAD

**Issue by kaminskypavel** [roninoss/create-expo-stack#433]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discord, in the #create-expo-stack channel.

```
❯  bunx create-expo-stack@latest
(node:3284) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
                          _
   ___  _ __  ___   __ _ | |_  ___
  / __|| '__|/ _ \ / _` || __|/ _ \
 | (__ | |  |  __/| (_| || |_|  __/
  \___||_|   \___| \__,_| \__|\___|
   ___ __  __ _ __    ___
  / _ \\ \/ /| '_ \  / _ \
 |  __/ >  < | |_) || (_) |
  \___|/_/\_\| .__/  \___/
       _     |_|        _
  ___ | |_  __ _   ___ | | __
 / __|| __|/ _` | / __|| |/ /
 \__ \| |_| (_| || (__ |   <
 |___/ \__|\__,_| \___||_|\_\

┌  Let's get started!
│
◇  What do you want to name your project?
│  create-expo-stack
│
◇  Would you like to use TypeScript with this project?
│  Yes
Good call, now using TypeScript! 🚀
│
◇
We've detected bun v1.1.34 as your preferred package manager.
Would you like to continue using it?
│  Yes
│
◇  What would you like to use for Navigation?
│  Expo Router
│
◇  What type of navigation would you like to use?
│  Stack
│
◇  What would you like to use for styling?
│  NativeWindUI
│
◇  Which components would you like to explore?
│  Action Sheet, Activity Indicator, Activity View, Avatar, Bottom Sheet, Date Picker, Picker, Progress Indicator, Ratings
Indicator, Slider, Toggle
You'll be styling with ease using NativeWindUI!
│
◇  What would you like to use for authentication?
│  None
No problem, skipping authentication for now.
│
◇  Do you want to setup EAS
│  Yes
We'll setup EAS for you.
│
◇  Would you like to save this configuration for future use?
│  No

Your project configuration:
{
  projectName: 'create-expo-stack',
  packages: [
    {
      name: 'expo-router',
      type: 'navigation',
      options: { type: 'stack' }
    },
    {
      name: 'nativewindui',
      type: 'styling',
      options: {
        selectedComponents: [
          'action-sheet',
          'activity-indicator',
          'activity-view',
          'avatar',
          'bottom-sheet',
          'date-picker',
          'picker',
          'progress-indicator',
          'ratings-indicator',
          'slider',
          'text',
          'toggle'
        ]
      }
    }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'bun',
    eas: true
  }
}

To recreate this project, run:
  npx create-expo-stack@latest create-expo-stack --nativewindui --bun --eas
│
◇  Project initialized!
│
◇  Base assets copied!
│
◇  Dependencies installed!
│
◇  Latest version of Expo installed!
│
◇  Packages updated!
│
node:internal/modules/cjs/loader:1246
  throw err;
  ^

**Error: Cannot find module 'C:\Users\user\AppData\Local\Temp\bunx-3530938197-nwui-cli@^0.4.1\node_modules\nwui-cli\build\index.js'**
    at Function._resolveFilename (node:internal/modules/cjs/loader:1243:15)
    at Function._load (node:internal/modules/cjs/loader:1068:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v23.2.0
◒  Adding nativewindui componentsError adding nativewindui components: {"stdout":null,"status":1,"error":null}
failed to run command: bunx nwui-cli@^0.4.1 add --yes -d create-expo-stack action-sheet activity-indicator activity-view avatar bottom-sheet date-picker picker progress-indicator ratings-indicator slider text toggle
■  Canceled

```

## Expected Behavior

this doesnt happen with latest version

## Possible Solution

looks like the issue stem from here 

https://github.com/roninoss/create-expo-stack/blob/41189684b32daf2b5889e8d4f7d27e072d529660/cli/src/utilities/generateNWUI.ts#L41

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dannyhw** [comment]
we're already using the latest version, not noticing any issue here, can you try running again and see if you still get the same issue?

**Comment by dannyhw** [comment]
latest updates have some fixes in, can you please give it another try?

**Comment by kaminskypavel** [comment]
@dannyhw still breaks [see logs below]. also even though im using `bun` it uses `npx` to installed the components

```bash

❯  bunx create-expo-stack@latest
(node:45272) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
                          _
   ___  _ __  ___   __ _ | |_  ___
  / __|| '__|/ _ \ / _` || __|/ _ \
 | (__ | |  |  __/| (_| || |_|  __/
  \___||_|   \___| \__,_| \__|\___|
   ___ __  __ _ __    ___
  / _ \\ \/ /| '_ \  / _ \
 |  __/ >  < | |_) || (_) |
  \___|/_/\_\| .__/  \___/
       _     |_|        _
  ___ | |_  __ _   ___ | | __
 / __|| __|/ _` | / __|| |/ /
 \__ \| |_| (_| || (__ |   <
 |___/ \__|\__,_| \___||_|\_\

┌  Let's get started!
│
◇  What do you want to name your project?
│  create-expo-stack
│
◇  Would you like to use TypeScript with this project?
│  Yes
Good call, now using TypeScript! 🚀
│
◇
We've detected bun v1.1.37 as your preferred package manager.
Would you like to continue using it?
│  Yes
│
◇  What would you like to use for Navigation?
│  Expo Router
│
◇  What type of navigation would you like to use?
│  Stack
│
◇  What would you like to use for styling?
│  NativeWindUI
│
◇  Which components would you like to explore?
│  Action Sheet, Activity Indicator, Activity View, Avatar, Bottom Sheet, Date Picker, Picker, Progress Indicator, Ratings
Indicator, Slider, Toggle
You'll be styling with ease using NativeWindUI!
│
◇  What would you like to use for authentication?
│  None
No problem, skipping authentication for now.
│
◇  Do you want to setup EAS
│  No
No problem, skipping eas for now.
│
◇  Would you like to save this configuration for future use?
│  No

Your project configuration:
{
  projectName: 'create-expo-stack',
  packages: [
    {
      name: 'expo-router',
      type: 'navigation',
      options: { type: 'stack' }
    },
    {
      name: 'nativewindui',
      type: 'styling',
      options: {
        selectedComponents: [
          'action-sheet',
          'activity-indicator',
          'activity-view',
          'avatar',
          'bottom-sheet',
          'date-picker',
          'picker',
          'progress-indicator',
          'ratings-indicator',
          'slider',
          'text',
          'toggle'
        ]
      }
    }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'bun',
    eas: false
  }
}

To recreate this project, run:
  npx create-expo-stack@latest create-expo-stack --nativewindui --bun
│
◇  Project initialized!
│
◇  Base assets copied!
│
◇  Dependencies installed!
│
◇  Latest version of Expo installed!
│
◇  Packages updated!
│
◓  Adding nativewindui components.(node:22148) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
  Received component metadata.
  Found expo-router.
Git status is dirty but the command will continue because EXPO_NO_GIT_STATUS is enabled...
⠼ Installing libraries and primitives...Error: Command failed with exit code 1: npx expo install @expo/react-native-action-sheet @gorhom/bottom-sheet react-native-gesture-handler @react-native-community/datetimepicker @react-native-picker/picker expo-store-review @react-native-community/slider @rn-primitives/avatar
(node:42252) ExperimentalWarning: CommonJS module C:\Users\user\AppData\Roaming\nvm\v23.2.0\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Users\user\AppData\Roaming\nvm\v23.2.0\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/modules/cjs/loader:1246
  throw err;
  ^

Error: Cannot find module 'c:\C:\Users\user\Desktop\create-expo-stack\node_modules\expo\bin\cli'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1243:15)
    at Function._load (node:internal/modules/cjs/loader:1068:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v23.2.0
    at makeError (file:///C:/Users/user/AppData/Local/Temp/bunx-3530938197-nwui-cli@%5E0.4.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///C:/Users/user/AppData/Local/Temp/bunx-3530938197-nwui-cli@%5E0.4.1/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async installComponent (file:///C:/Users/user/AppData/Local/Temp/bunx-3530938197-nwui-cli@%5E0.4.1/node_modules/nwui-cli/build/install-component.js:122:29)
    at async main (file:///C:/Users/user/AppData/Local/Temp/bunx-3530938197-nwui-cli@%5E0.4.1/node_modules/nwui-cli/build/index.js:63:17) {
  shortMessage: 'Command failed with exit code 1: npx expo install @expo/react-native-action-sheet @gorhom/bottom-sheet react-native-gesture-handler @react-native-community/datetimepicker @react-native-picker/picker expo-store-review @react-native-community/slider @rn-primitives/avatar',
  command: 'npx expo install @expo/react-native-action-sheet @gorhom/bottom-sheet react-native-gesture-handler @react-native-community/datetimepicker @react-native-picker/picker expo-store-review @react-native-community/slider @rn-primitives/avatar',
  escapedCommand: 'npx expo install "@expo/react-native-action-sheet" "@gorhom/bottom-sheet" react-native-gesture-handler "@react-native-community/datetimepicker" "@react-native-picker/picker" expo-store-review "@react-native-community/slider" "@rn-primitives/avatar"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '(node:42252) ExperimentalWarning: CommonJS module C:\\Users\\user\\AppData\\Roaming\\nvm\\v23.2.0\\node_modules\\npm\\node_modules\\debug\\src\\node.js is loading ES Module C:\\Users\\user\\AppData\\Roaming\\nvm\\v23.2.0\\node_modules\\npm\\node_modules\\supports-color\\index.js using require().\n' +
    'Support for loading ES Module in require() is an experimental feature and might change at any time\n' +
    '(Use `node --trace-warnings ...` to show where the warning was created)\n' +
    'node:internal/modules/cjs/loader:1246\r\n' +
    '  throw err;\r\n' +
    '  ^\r\n' +
    '\r\n' +
    "Error: Cannot find module 'c:\\C:\\Users\\user\\Desktop\\create-expo-stack\\node_modules\\expo\\bin\\cli'\r\n" +
    '    at Function._resolveFilename (node:internal/modules/cjs/loader:1243:15)\r\n' +
    '    at Function._load (node:internal/modules/cjs/loader:1068:27)\r\n' +
    '    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\r\n' +
    '    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)\r\n' +
    '    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)\r\n' +
    '    at node:internal/main/run_main_module:36:49 {\r\n' +
    "  code: 'MODULE_NOT_FOUND',\r\n" +
    '  requireStack: []\r\n' +
    '}\r\n' +
    '\r\n' +
    'Node.js v23.2.0',
  cwd: 'c:\\Users\\user\\Desktop\\create-expo-stack',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
npx expo install failed
◇  Canceled
⠸ Installing libraries and primitives..

```

**Comment by dannyhw** [comment]
First thing is that with bunx @latest doesnt work it uses a cached version. Can you try specifying the exact version.

Secondly if you want to force it to use bunx in ces then pass --bun

**Comment by danstepanov** [comment]
I'm able to generate a project following OPs instructions, I'm using bun 1.1.25 though. Closing this for now.
